---
- name: "[HAPROXY]- apt update"
  apt:
    update-cache: yes
    cache_valid_time: 3600
- name: "[HAPROXY] install haproxy"
  apt:
    name: haproxy
    state: present
- name: "[HAPROXY] - start service"
  service: 
    name: haproxy
    state: started
...
