[haproxy]
192.168.205.11
                                                                                                                                                                
[consul]
192.168.205.12 
#192.168.205.13
[myapp]
192.168.205.14


